version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name          = "cmsc471-final"
resolve_s3          = true
region              = "us-east-1"
confirm_changeset   = true
capabilities        = "CAPABILITY_IAM"
parameter_overrides = "DBPassword=Cmsc471Lab!"
